/* The following code was generated by JFlex 1.4.3 on 31/8/24, 12:38 */

package lyc.compiler;

import java_cup.runtime.Symbol;
import lyc.compiler.ParserSym;
import lyc.compiler.model.*;
import static lyc.compiler.constants.Constants.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 31/8/24, 12:38 from the specification file
 * <tt>/Users/francosabes/Desktop/Compilador/java/compiler-java-main/src/main/jflex/lexer.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\12\1\35"+
    "\3\0\1\13\1\0\1\26\1\27\1\21\1\20\1\24\1\22\1\25"+
    "\1\23\12\34\2\0\1\16\1\17\1\15\2\0\2\4\1\4\2\4"+
    "\1\4\2\4\1\4\11\4\1\4\7\4\1\32\1\0\1\33\3\0"+
    "\1\4\1\4\1\4\1\4\1\7\1\10\1\4\1\4\1\5\2\4"+
    "\1\6\1\4\1\4\1\4\2\4\1\4\1\11\1\4\1\4\1\4"+
    "\1\4\1\4\1\4\1\4\1\30\1\14\1\31\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\3\3\3\4\1\5\2\2\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\1\1\2\1\0"+
    "\1\4\1\25\1\4\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\2\0\1\1\2\0\1\4\1\0"+
    "\1\1\1\0\1\36\1\37\1\40\1\37\1\1\1\0"+
    "\1\37\1\1\1\0\1\37\1\1\1\0\1\37\1\1"+
    "\1\0\1\37\1\1\1\0\1\37\1\1\1\0\1\37"+
    "\1\1\1\0\1\37\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\32\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\36\0\74\0\132\0\36\0\170\0\226\0\264"+
    "\0\322\0\360\0\u010e\0\u012c\0\u014a\0\u0168\0\36\0\u0186"+
    "\0\36\0\u01a4\0\36\0\36\0\36\0\36\0\36\0\36"+
    "\0\36\0\36\0\u01c2\0\u01e0\0\u01fe\0\u021c\0\u021c\0\u023a"+
    "\0\132\0\132\0\132\0\132\0\132\0\132\0\132\0\132"+
    "\0\36\0\u0258\0\u0276\0\u0294\0\u02b2\0\u02d0\0\u02ee\0\u030c"+
    "\0\u032a\0\132\0\u0348\0\u021c\0\u02b2\0\u0366\0\u0384\0\u03a2"+
    "\0\u03c0\0\u03de\0\u03fc\0\u041a\0\u0438\0\u0456\0\u0474\0\u0492"+
    "\0\u04b0\0\u04ce\0\u04ec\0\u050a\0\u0528\0\u0546\0\u0564\0\u0582"+
    "\0\u05a0\0\132\0\u05be\0\u05dc\0\u05fa\0\u0618\0\u0636\0\u0654"+
    "\0\u0672\0\u0690\0\u06ae\0\u06cc\0\132\0\u06ea\0\u0708\0\u0726"+
    "\0\u0744\0\u0762\0\u0780\0\u079e\0\u07bc\0\u07da\0\u07f8\0\u0816"+
    "\0\u0834\0\u0852\0\u0870\0\u088e\0\u08ac\0\u08ca\0\u08e8\0\u0906"+
    "\0\u0924\0\u0942\0\u0960\0\u097e\0\u099c\0\u09ba\0\u09d8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\6\1\10"+
    "\2\6\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\25\0\1\35\12\0"+
    "\1\4\22\0\1\35\52\0\6\36\13\0\1\35\6\0"+
    "\1\36\5\0\4\36\1\37\1\36\13\0\1\35\6\0"+
    "\1\36\5\0\2\36\1\40\3\36\13\0\1\35\6\0"+
    "\1\36\20\0\1\41\5\0\1\35\23\0\1\42\11\0"+
    "\1\35\24\0\1\43\10\0\1\35\27\0\1\44\5\0"+
    "\1\35\27\0\1\45\5\0\1\35\27\0\1\46\5\0"+
    "\1\35\33\0\1\47\1\0\1\35\31\0\1\50\3\0"+
    "\1\35\10\0\2\51\1\0\22\51\1\52\6\51\1\53"+
    "\1\51\4\0\6\54\13\0\1\35\6\0\1\54\1\0"+
    "\2\55\1\0\33\55\4\0\6\36\22\0\1\36\5\0"+
    "\5\36\1\56\22\0\1\36\1\0\2\55\1\0\22\55"+
    "\1\57\10\55\2\51\1\0\22\51\1\52\6\51\1\60"+
    "\1\51\4\0\6\61\22\0\1\61\1\62\34\0\1\63"+
    "\5\0\3\36\1\64\2\36\22\0\1\36\1\0\2\55"+
    "\1\0\31\55\1\65\1\55\2\51\1\0\22\51\1\52"+
    "\6\51\1\66\1\51\4\0\6\67\22\0\1\67\1\62"+
    "\34\0\1\70\1\0\2\51\1\0\22\51\1\52\6\51"+
    "\1\71\1\51\4\0\6\72\22\0\1\72\1\62\34\0"+
    "\1\73\1\0\2\51\1\0\22\51\1\52\6\51\1\74"+
    "\1\51\4\0\6\75\22\0\1\75\1\62\34\0\1\76"+
    "\1\0\2\51\1\0\22\51\1\52\6\51\1\77\1\51"+
    "\4\0\6\100\22\0\1\100\1\62\34\0\1\101\1\0"+
    "\2\51\1\0\22\51\1\52\6\51\1\102\1\51\4\0"+
    "\6\103\22\0\1\103\1\62\34\0\1\104\1\0\2\51"+
    "\1\0\22\51\1\52\6\51\1\105\1\51\4\0\6\106"+
    "\22\0\1\106\1\62\34\0\1\107\26\0\1\35\6\0"+
    "\1\110\5\0\6\111\22\0\1\111\1\62\34\0\1\112"+
    "\35\0\1\113\5\0\6\114\22\0\1\114\1\62\34\0"+
    "\1\115\5\0\6\116\22\0\1\116\1\62\34\0\1\117"+
    "\5\0\6\120\22\0\1\120\1\62\34\0\1\121\5\0"+
    "\6\122\22\0\1\122\1\62\34\0\1\123\5\0\6\124"+
    "\22\0\1\124\1\62\34\0\1\125\5\0\6\126\22\0"+
    "\1\126\1\62\4\0\6\127\22\0\1\127\1\62\4\0"+
    "\6\130\22\0\1\130\1\62\4\0\6\131\22\0\1\131"+
    "\1\62\4\0\6\132\22\0\1\132\1\62\4\0\6\133"+
    "\22\0\1\133\1\62\4\0\6\134\22\0\1\134\1\62"+
    "\4\0\6\135\22\0\1\135\1\62\4\0\6\136\22\0"+
    "\1\136\1\62\4\0\6\137\22\0\1\137\1\62\4\0"+
    "\6\140\22\0\1\140\1\62\4\0\6\141\22\0\1\141"+
    "\1\62\4\0\6\142\22\0\1\142\1\62\4\0\6\143"+
    "\22\0\1\143\1\62\4\0\6\144\22\0\1\144\1\62"+
    "\4\0\6\145\22\0\1\145\1\62\4\0\6\146\22\0"+
    "\1\146\1\62\4\0\6\147\22\0\1\147\1\62\4\0"+
    "\6\150\22\0\1\150\1\62\4\0\6\151\22\0\1\151"+
    "\1\62\4\0\6\152\22\0\1\152\1\62\4\0\6\153"+
    "\22\0\1\153\1\62\4\0\6\154\22\0\1\154\1\62"+
    "\4\0\6\155\22\0\1\155\1\62\4\0\6\156\22\0"+
    "\1\156\1\62\4\0\6\157\22\0\1\157\1\62\35\0"+
    "\1\62";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2550];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\1\1\11\30\1\1\0\3\1\10\11\2\0\1\1"+
    "\2\0\1\1\1\0\1\1\1\0\1\11\4\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\0\1\11\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\11"+
    "\32\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 136) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, CompilerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 6: 
          { return symbol(ParserSym.OP_GREATER);
          }
        case 33: break;
        case 16: 
          { return symbol(ParserSym.CLOSE_BRACKET);
          }
        case 34: break;
        case 14: 
          { return symbol(ParserSym.DOT);
          }
        case 35: break;
        case 9: 
          { return symbol(ParserSym.PLUS);
          }
        case 36: break;
        case 27: 
          { return symbol(ParserSym.OP_EQUAL);
          }
        case 37: break;
        case 29: 
          { return symbol(ParserSym.OPEN_COMMENT);
          }
        case 38: break;
        case 28: 
          { return symbol(ParserSym.CLOSE_COMMENT);
          }
        case 39: break;
        case 23: 
          { return symbol(ParserSym.AND);
          }
        case 40: break;
        case 19: 
          { return symbol(ParserSym.OPEN_SQUARE_BRACKET);
          }
        case 41: break;
        case 5: 
          { return symbol(ParserSym.NOT);
          }
        case 42: break;
        case 26: 
          { return symbol(ParserSym.OP_LESSER_EQUAL);
          }
        case 43: break;
        case 24: 
          { return symbol(ParserSym.OR);
          }
        case 44: break;
        case 11: 
          { return symbol(ParserSym.SUB);
          }
        case 45: break;
        case 12: 
          { return symbol(ParserSym.DIV);
          }
        case 46: break;
        case 31: 
          { return symbol(ParserSym.CONST_FLOAT, yytext());
          }
        case 47: break;
        case 1: 
          { return symbol(ParserSym.CONST_INT, yytext());
          }
        case 48: break;
        case 20: 
          { return symbol(ParserSym.CLOSE_SQUARE_BRACKET);
          }
        case 49: break;
        case 10: 
          { return symbol(ParserSym.MULT);
          }
        case 50: break;
        case 15: 
          { return symbol(ParserSym.OPEN_BRACKET);
          }
        case 51: break;
        case 13: 
          { return symbol(ParserSym.COMMA);
          }
        case 52: break;
        case 17: 
          { return symbol(ParserSym.OPEN_KEY_BRACKET);
          }
        case 53: break;
        case 22: 
          { return symbol(ParserSym.OP_NOT_EQUAL);
          }
        case 54: break;
        case 32: 
          { return symbol(ParserSym.ELSE);
          }
        case 55: break;
        case 21: 
          { return symbol(ParserSym.IF);
          }
        case 56: break;
        case 2: 
          { throw new UnknownCharacterException(yytext());
          }
        case 57: break;
        case 7: 
          { return symbol(ParserSym.OP_LESSER);
          }
        case 58: break;
        case 30: 
          { return symbol(ParserSym.CONST_STRING, yytext());
          }
        case 59: break;
        case 25: 
          { return symbol(ParserSym.OP_GREATER_EQUAL);
          }
        case 60: break;
        case 4: 
          { return symbol(ParserSym.IDENTIFIER, yytext());
          }
        case 61: break;
        case 8: 
          { return symbol(ParserSym.OP_ASSIG);
          }
        case 62: break;
        case 18: 
          { return symbol(ParserSym.CLOSE_KEY_BRACKET);
          }
        case 63: break;
        case 3: 
          { /* ignore */
          }
        case 64: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   return symbol(ParserSym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
