
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lyc.compiler;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int SPACE = 25;
  public static final int MULT = 23;
  public static final int OP_LESSER_EQUAL = 17;
  public static final int OP_GREATER = 14;
  public static final int INT = 6;
  public static final int INIT = 5;
  public static final int WRITE = 12;
  public static final int NOT = 9;
  public static final int AND = 10;
  public static final int CLOSE_SQUARE_BRACKET = 35;
  public static final int OR = 11;
  public static final int COMMA = 28;
  public static final int OP_NOT_EQUAL = 19;
  public static final int DIV = 24;
  public static final int CONST_FLOAT = 39;
  public static final int PLUS = 21;
  public static final int IF = 3;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int OP_ASSIG = 20;
  public static final int error = 1;
  public static final int OPEN_SQUARE_BRACKET = 34;
  public static final int OP_LESSER = 15;
  public static final int OPEN_KEY_BRACKET = 30;
  public static final int CLOSE_BRACKET = 33;
  public static final int OPEN_BRACKET = 32;
  public static final int CLOSE_COMMENT = 27;
  public static final int OPEN_COMMENT = 26;
  public static final int OP_GREATER_EQUAL = 16;
  public static final int ELSE = 4;
  public static final int READ = 13;
  public static final int WHILE = 2;
  public static final int CLOSE_KEY_BRACKET = 31;
  public static final int FLOAT = 7;
  public static final int CONST_STRING = 41;
  public static final int STRING = 8;
  public static final int BINARY_COUNT = 37;
  public static final int OP_EQUAL = 18;
  public static final int TRIANGLE = 36;
  public static final int SUB = 22;
  public static final int CONST_INT = 40;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WHILE",
  "IF",
  "ELSE",
  "INIT",
  "INT",
  "FLOAT",
  "STRING",
  "NOT",
  "AND",
  "OR",
  "WRITE",
  "READ",
  "OP_GREATER",
  "OP_LESSER",
  "OP_GREATER_EQUAL",
  "OP_LESSER_EQUAL",
  "OP_EQUAL",
  "OP_NOT_EQUAL",
  "OP_ASSIG",
  "PLUS",
  "SUB",
  "MULT",
  "DIV",
  "SPACE",
  "OPEN_COMMENT",
  "CLOSE_COMMENT",
  "COMMA",
  "DOT",
  "OPEN_KEY_BRACKET",
  "CLOSE_KEY_BRACKET",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_SQUARE_BRACKET",
  "CLOSE_SQUARE_BRACKET",
  "TRIANGLE",
  "BINARY_COUNT",
  "IDENTIFIER",
  "CONST_FLOAT",
  "CONST_INT",
  "CONST_STRING"
  };
}

